spring.application.name=todo_api

#MySQL Database Connection

spring.datasource.url = jdbc:mysql://localhost:3306/todo_cse
spring.datasource.username = root
spring.datasource.password = malathi@1924

#JPA/Hibernate orm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server Port
server.port=8080